const COLOR_DEFAULT = "#007AFF";
const COLOR_DEFAULT_TEXT= "#000";
const COLOR_DEFAULT_BUTTON_TEXT = "rgb(255,255,255)";
const COLOR_BLUE = "rgb(0, 122, 255)";

export {
    COLOR_DEFAULT,
    COLOR_DEFAULT_TEXT,
    COLOR_DEFAULT_BUTTON_TEXT,
    COLOR_BLUE
}
